name: qurator

on:
  push:
    branches:
      qaleph

jobs:
  docker-ui:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build development image
      run: |
        docker build -t malteos/aleph-ui:${GITHUB_SHA} ui
        docker tag malteos/aleph-ui:${GITHUB_SHA} malteos/aleph-ui:latest
    - name: Build production image
      run: |
        docker build -t malteos/aleph-ui-production:${GITHUB_SHA} -f qurator/ui/Dockerfile.production ui
    - name: Push docker image (hash)
      run: |
        docker login -u ${{ secrets.docker_user }} -p ${{ secrets.docker_password }}
        docker push malteos/aleph-ui-production:${GITHUB_SHA}
  docker-elasticsearch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build docker image
      run: |
        docker build -t malteos/aleph-elasticsearch:${GITHUB_SHA} services/elasticsearch
        docker tag malteos/aleph-elasticsearch:${GITHUB_SHA} malteos/aleph-elasticsearch:latest
    - name: Push docker image (hash)
      run: |
        docker login -u ${{ secrets.docker_user }} -p ${{ secrets.docker_password }}
        docker push malteos/aleph-elasticsearch:${GITHUB_SHA}
  docker-ingest-file:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build docker image
      run: |
        docker build -t malteos/ingest-file:${GITHUB_SHA} services/ingest-file
        docker tag malteos/ingest-file:${GITHUB_SHA} malteos/ingest-file:latest
    - name: Push docker image (hash)
      run: |
        docker login -u ${{ secrets.docker_user }} -p ${{ secrets.docker_password }}
        docker push malteos/ingest-file:${GITHUB_SHA}
  docker-qurator-cwm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build docker image
      run: |
        docker build -t malteos/qurator-cwm:${GITHUB_SHA} services/qurator-cwm
        docker tag malteos/qurator-cwm:${GITHUB_SHA} malteos/qurator-cwm:latest
    - name: Push docker image (hash)
      run: |
        docker login -u ${{ secrets.docker_user }} -p ${{ secrets.docker_password }}
        docker push malteos/qurator-cwm:${GITHUB_SHA}
  docker-aleph:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build docker image
      run: |
        docker build --cache-from malteos/aleph:latest -t malteos/aleph:${GITHUB_SHA} .
        docker tag malteos/aleph:${GITHUB_SHA} malteos/aleph:latest
    - name: Push docker image (hash)
      run: |
        docker login -u ${{ secrets.docker_user }} -p ${{ secrets.docker_password }}
        docker push malteos/aleph:${GITHUB_SHA}
  test-aleph:
    runs-on: ubuntu-latest
    needs:
    - docker-aleph
    - docker-elasticsearch
    - docker-ingest-file
    - docker-qurator-cwm
    - docker-ui
    steps:
    - uses: actions/checkout@v1
    - name: Set up
      run: |
        sudo sysctl -w vm.max_map_count=262144
        sudo echo "ALEPH_SECRET=batman\n" >> aleph.env
        docker --version
        docker-compose --version
    - name: Docker pull and start
      run: |
        echo "${GITHUB_REF}"
        cd qurator
        ALEPH_TAG=${GITHUB_SHA} docker-compose pull --quiet --parallel elasticsearch convert-document ingest-file worker cwm
        make ALEPH_TAG=${GITHUB_SHA} services
        sleep 10
    - name: Run ingest tests
      run: |
        cd qurator
        make ALEPH_TAG=${GITHUB_SHA} ingest-test
    - name: Run aleph tests
      run: |
        cd qurator
        make ALEPH_TAG=${GITHUB_SHA} test
#    - name: Push docker images for tags
#      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
#      run: |
#        export ALEPH_TAG=${GITHUB_REF/refs\/tags\//}
#        docker login -u ${{ secrets.docker_user }} -p ${{ secrets.docker_password }}
#        docker pull malteos/aleph-ui-production:${GITHUB_SHA}
#        for IMAGE in aleph aleph-ui-production aleph-elasticsearch ingest-file; do
#          docker tag malteos/${IMAGE}:${GITHUB_SHA} malteos/${IMAGE}:${ALEPH_TAG};
#          docker push malteos/${IMAGE}:${ALEPH_TAG};
#          docker tag malteos/${IMAGE}:${GITHUB_SHA} malteos/${IMAGE}:latest;
#          docker push malteos/${IMAGE}:latest;
#        done;
    - name: Push docker images for tags
      run: |
        docker login -u ${{ secrets.docker_user }} -p ${{ secrets.docker_password }}
        docker pull malteos/aleph-ui-production:${GITHUB_SHA}
        for IMAGE in aleph aleph-ui-production aleph-elasticsearch ingest-file qurator-cwm; do
          docker tag malteos/${IMAGE}:${GITHUB_SHA} malteos/${IMAGE}:latest;
          docker push malteos/${IMAGE}:latest;
        done;
